# Generated by Django 4.2.7 on 2023-11-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='carouselimage',
            name='page',
        ),
        migrations.AddField(
            model_name='homepage',
            name='caption',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='CarouselContent',
        ),
        migrations.DeleteModel(
            name='CarouselImage',
        ),
    ]
