# Generated by Django 4.2.7 on 2023-11-25 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_homepage_caption_carouselimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='image',
        ),
    ]
