# Generated by Django 4.2.10 on 2024-03-05 16:31

from django.db import migrations
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_homepage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='logos',
            field=wagtail.fields.StreamField([('logo', wagtail.images.blocks.ImageChooserBlock())], blank=True, use_json_field=True),
        ),
    ]
