# Generated by Django 4.2.10 on 2024-03-06 18:46

from django.db import migrations
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_productfirstmenu_productpage_productsecondmenu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productthirdmenu',
            name='images',
            field=wagtail.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, use_json_field=True),
        ),
    ]
