# Generated by Django 4.2.10 on 2024-03-07 11:37

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_controlimages_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlimages',
            name='images',
            field=wagtail.fields.StreamField([('image_block', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.blocks.RichTextBlock(required=False)), ('link', wagtail.blocks.URLBlock(help_text='Hyperlink to another website', max_length=255, required=False))]))], blank=True, use_json_field=True),
        ),
    ]
