# Generated by Django 4.2.10 on 2024-03-10 07:41

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_controlimages_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfirstmenu',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='productfirstmenu',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productsecondmenu',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='productsecondmenu',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productthirdmenu',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='productthirdmenu',
            name='product',
        ),
        migrations.RemoveField(
            model_name='royalimages',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='name',
        ),
        migrations.AddField(
            model_name='productpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='images',
            field=wagtail.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.blocks.RichTextBlock(required=False))], blank=True, use_json_field=True),
        ),
        migrations.DeleteModel(
            name='ControlImages',
        ),
        migrations.DeleteModel(
            name='ProductFirstMenu',
        ),
        migrations.DeleteModel(
            name='ProductSecondMenu',
        ),
        migrations.DeleteModel(
            name='ProductThirdMenu',
        ),
        migrations.DeleteModel(
            name='RoyalImages',
        ),
    ]
