# Generated by Django 4.2.10 on 2024-03-10 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('home', '0015_alter_productpage_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductPage',
            new_name='ControlImages',
        ),
    ]
